name: Docker Image CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login on Yandex.Cloud Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: cr.yandex
        username: oauth
        password: ${{ secrets.YANDEX_CLOUD_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.BOX_REGISTRY }}/box-back
    - name: Push to Yandex.Cloud Registry
      run: docker push ${{ secrets.BOX_REGISTRY }}/box-back
